name:                hizardry
version:             0.1.0.0
github:              "GoodSeat/hizardry"
license:             BSD3
author:              "GoodSeat"
maintainer:          "GoodSeat@hotmail.co.jp"
copyright:           "2019-2026 GoodSeat"

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- NoImplicitPrelude

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/GoodSeat/hizardry#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- arrows
- random
- directory
- containers
- ansi-terminal
- parsec
- async
- process

library:
  source-dirs: 
  - src

executables:
  hizardry-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts
    - --io-manager=native
    dependencies:
    - hizardry

tests:
  hizardry-test:
    main:                HspecRunner.hs
    source-dirs:         test/hspec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hizardry
    - hspec
    - doctest

  hizardry-doctest:
    main:                DocTest.hs
    source-dirs:         test/doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hizardry
    - doctest
    - hspec
